### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by pcav** [bullocke/ROI_Plugin#2]
Traceback (most recent call last):
              File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 294, in startPlugin
                plugins[packageName] = package.classFactory(iface)
              File "/home/paolo/.qgis2/python/plugins/roitool/**init**.py", line 34, in classFactory
                from .roitool import ROITool
              File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/paolo/.qgis2/python/plugins/roitool/roitool.py", line 31, in <module>
                from roitool_dialog import ROIToolDialog
              File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/paolo/.qgis2/python/plugins/roitool/roitool_dialog.py", line 43, in <module>
                from .plot import ROIPlot
              File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/paolo/.qgis2/python/plugins/roitool/plot.py", line 15, in <module>
                mpl_version = map(int, mpl.__version__.split('.'))
            ValueError: invalid literal for int() with base 10: '0rc2'

**Comment by ceholden** [comment]
Thank you for the report, Paolo. The error comes from a silly way of checking for matplotlib's version which broke for `v1.5.0rc2`. The commit reference above removes the version checking in favor of an EAFP approach.

I've uploaded the fix to the QGIS plugin repository for `v0.1.1` that fixes this bug.

**Comment by ceholden** [comment]
Plugin has been updated and approved in QGIS repository. Version `v0.1.1` has fix applied.
